# Fetching latest version of Java
FROM openjdk:17-jdk-alpine
 
# Copy the jar file into our app
COPY /target/costoconversion-0.0.1-SNAPSHOT.jar java_app.jar 
COPY /src/main/resources/application.properties application.properties


# Exposing port 8080
EXPOSE 8080

# Starting the application
ENTRYPOINT ["java", "-jar", "java_app.jar"]