version: '3.9'

services:
  java_db_postgres:
    image: postgres:15
    container_name: java_db_postgres
    environment:
      POSTGRES_DB: conversion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - java_network

  java_spring_boot:
    build: .
    image: costoconversion-java_app
    container_name: java_spring_boot
    depends_on:
      - java_db_postgres
    ports:
      - "8080:8080"
    networks:
      - java_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java_db_postgres:5432/conversion
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

networks:
  java_network:
    driver: bridge
